apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: store-ui
    version: v1
  name: store-ui
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: store-ui
    version: v1
  type: NodePort
status:
  loadBalancer: {}
